apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chart-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key : label-value  
    spec:
      containers:
        - name: chart-ui-container
          image: amaraneniakash/angular-chart-ui
          imagePullPolicy: Always
          ports:
          - containerPort: 80